### ISSUE TITLE
Code Reader

### ISSUE THREAD

**Issue by erkekin** [alexisakers/QuickCode#3]
do you consider adding a barcode reader into the app? In case any cam is connected we can request access to it and we can decode the barcode. 

If you'd like it I can implement it.

**Comment by alexaubry** [comment]
It would be an interesting feature, but it doesnt really fit the use case I originally had in mind, which was to generate barcodes for testing. I personally think it would be cool to have something like the 1Password QR code scanner, as a separate app! Let me know if you ever build it, would be happy to give it a try.
